<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_NCI" Id="{a10e90fe-73ba-4e2b-a9a5-81d463ea7a9b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_NCI
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	test : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test := TRUE;]]></ST>
    </Implementation>
    <LineIds Name="FB_NCI">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>